# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'intf', 'is_cat', 'classify_image']

# %% app.ipynb 1
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 3
learn=load_learner('model.pkl')

# %% app.ipynb 5
categories=('Dog','Cat')

def classify_image(img):
    pred,idx,probs=learn.predict(img)
    return dict(zip(categories,map(float,probs)))

# %% app.ipynb 7
intf=gr.Interface(fn=classify_image,inputs=gr.Image(height=500,width=500,type="pil"),outputs=gr.Label(),examples=['dog.jpg', 'cat.jpg','dunno.jpg'])
intf.launch(inline=False)
